### ISSUE TITLE
Several variants for non interactive exercises 

### ISSUE THREAD

**Issue by bothmer** [frankluebeck/OKUSON#5]
It would be great, if one could also provide several variants for non interactive exercises. 

We do this all the time, but must then disguise these non interactive exercises  as interactive by choosing "s" an adding a text "please leave the answer space for this exercise blank".

**Comment by frankluebeck** [comment]
This would be a lot of work, because changes in many places would be needed (starting from inventing  a syntax to specify such variants for non-interactive exercises). I cannot find to implement and test such a feature.

Also, for the marking how would  tutors know which exercise is treated? And wouldn't that be a lot of extra effort for tutors, if several variants of each exercise exist?

**Comment by bothmer** [comment]
Thanks for your answer! If it is too much work, we can continue with writing "leave the answer space blank"

> Also, for the marking how would tutors know which exercise is treated?
We require the students to attach a printout of the PDF-Sheet.

> And wouldn't that be a lot of extra effort for tutors, if several variants of each exercise exist?
Indeed this is extra work for the tutors. I still think it is worth it, because different variants let students work together in groups without some only copying the answers from others.

Also we sometime use both online and written solutions for the same exercise. In the first semester of a stochastic course I had interactive exercises where only the answer had to be entered. But then in the final exam the students were not able to write down their solution in a readable manner. So in the following semesters we required them to enter the answer online and still hand in their  calculations. The Tutors then only check if the calculations were written down in a readable manner. The correctness is checked by OKUSON.
